[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
lib_deps = 
    mikalhart/TinyGPSPlus @ ^1.0.3
    adafruit/Adafruit BME280 Library @ ^2.2.2
    adafruit/Adafruit BNO055 @ ^1.6.1
    ; Need to include the MAVLink C headers